---
title: "vizhw1"
author: "Stephanie Beard"
date: "9/08/2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
d1 <- diamonds
```

```{r}
ggplot(d1, aes(x = carat, y = price)) +
  geom_point(aes(color = as.character(clarity)), alpha = 0.3) +
  ggtitle("Scatterplot of Diamond Prices") +
  xlab("Diamond Carats") +
  ylab("Diamond Price") +
  scale_color_discrete() +
  theme_light()
```

```{r}
ggplot(d1, aes(carat, price)) +
  theme_light() +
  theme(strip.text = element_text(colour = 'black')) +
  geom_point(aes(color = clarity), alpha = 0.3) +
  facet_wrap(~clarity) +
  ggtitle("Scatterplot of Diamond Prices") +
  xlab("Diamond Carats") +
  ylab("Diamond Price") +
  scale_color_discrete() +
  theme(legend.position = "none") 
```

```{r}
ggplot(d1, aes(x = table, y = price)) +
  geom_smooth(method = 'gam', linetype = 2, color = "red") +
  xlab("Table") +
  ylab("Price") +
  theme_light()
```

```{r}
ggplot(d1, aes(x = depth, y = price)) +
  geom_smooth(method = 'gam', linetype = 2, color = "white") +
  xlab("Depth") +
  ylab("Price") +
  theme_light()
```

```{r}
ggplot(d1, aes(x = price)) +
  geom_bar() +
  theme_light()
```

```{r}
ggplot(d1, aes(price)) +
  geom_histogram() +
  theme_light()
```

```{r}
ggplot(d1, aes(clarity)) +
  theme_light() +
  geom_bar(aes(fill = clarity)) +
  theme(legend.position = "none") 
```

```{r}
ggplot(d1, aes(cut, depth)) +
  geom_violin(color = "blue") +
  geom_jitter(alpha = 0.1, color = "red") +
  theme_light()
```

```{r}
ggplot(d1, aes(x = x, y = price)) +
  geom_smooth(se = FALSE, color = "blue") +
  geom_smooth(method ="lm", se = FALSE, color = "green") +
  theme_light()
```

