---
title: "Hw2"
author: "Stephanie Beard"
date: "9/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
e1<-economics
```

```{r}

#Question 1

pres2 <- subset(presidential, start > e1$date[1])

ggplot(data = e1) +
    geom_rect(data = pres2, aes(ymin = -Inf, ymax = Inf, xmin 
= start, xmax = end, fill =party),alpha=.9) + 
  scale_fill_manual(values = c("blue", "red")) +
   geom_vline(
         aes(xintercept = as.numeric(start)),
         data = pres2,
         colour = "grey", alpha = 0.5) +
  geom_text(aes(
    x = start,
    y = 2500, label = name),
  data = pres2,
  size = 3.8,
  vjust = c(3,1.3,2.1,3,2,4,4,4),
  hjust = 0.1,
  fontface="bold",
  family = "Impact",
    color = "white",
  angle = 90) +
  geom_line(data=e1, aes(x=date, y=unemploy),
          color="white",size=1.2) +
  labs(x="Year",y="Unemployment '000", fill = "Party") +
  scale_x_date(breaks = pres2$start, labels = scales::date_format("%m-%Y"))+
 theme(panel.background =element_rect(fill="white"),
        axis.line=element_line(color="black"),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text=element_text(color="black",size=8))
```

```{r}
#Question 2
ggplot(data = e1) +
    geom_rect(data = pres2, aes(ymin = -Inf, ymax = Inf, xmin 
= start, xmax = end, fill =party),alpha=.9) + 
  scale_fill_manual(values = c("blue", "red")) +
   geom_vline(
        aes(xintercept = as.numeric(start)),
         data = pres2,
         colour = "grey", alpha = 0.5) +
  geom_text(aes(
    x = start,
    y = 25, label = name),
  data = pres2,
  vjust = c(3,1.3,3,3,2,4,4,4),
  hjust = 0,
    angle = 90,size = 3.8, color = "white", family = "Arial", nudge_x = 50) +
  geom_line(data=e1, aes(x=date, y=uempmed),
          color="white",size=1.2) +
  labs(x="Year",y="Median Duration of Unemployment (Weeks)", fill = "Party") +
  scale_y_continuous(limits = c(0,30))+
    scale_x_date(breaks = pres2$start, labels = scales::date_format("%Y-%m-%d"))+
 theme(panel.background =element_rect(fill="white"),
        axis.line=element_line(color="black"),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text=element_text(color="black",size=8))
```

